### ISSUE TITLE
multiple select box for blueprint

### ISSUE THREAD

**Issue by hirao-k** [thanhtetaung/building-web#13]
- ~"面積表", "平面図"~
  - ~[ ] change "階" `input number` to `select box`~
    - ~selectable values area "指定なし" and 1, ... "地上階数"~ 
      - ~ex. when "地上階数" is 3, selectable values area "指定なし" 1, 2, 3~
- [ ] after select value, add new input or select for
  - "面積表", "平面図" : "階" `input`
  - "立面図", "断面図" : "方角" `select box`

![image](https://user-images.githubusercontent.com/8351733/122356439-c3f6c580-cf8d-11eb-9f50-7f76545c8bc3.png)

**Comment by hirao-k** [comment]
add new "階" select box, after select "階" select box. 
![image](https://user-images.githubusercontent.com/8351733/122389984-78074900-cfac-11eb-854b-04148c95d6cb.png)

**Comment by hirao-k** [comment]
https://komugi-lab.slack.com/archives/C015DS32012/p1623982336000700?thread_ts=1623916821.003300&cid=C015DS32012

> I feel strange for that kind of controls. I think you are asking user to indicate that each image (page of pdf) is for which floors (I assume it’s more than one floor. Normally it should be for one floor). But think about user experience with large number of floors. Let’s say if there is 10 number of floors above ground and each image represent single floor, user always get 10 dropdown controls for each image and have to choose 9 controls to 指定なし.

**Comment by thanhtetaung** [comment]
@hirao-k  It will be still too many controls if one image is represent one floor case. Example if there are 10 floors and one image represent one floor, user will fill only one text box of 10 every time. UI will be ugly. I think there are better 3 options:

1. [multi select dropdown](https://material.angular.io/components/select/overview) (downside is selected value won’t be shown if too many) 
2. [tag/chip selector](https://material.angular.io/components/chips/overview)
3. single text box/dropdown with add more button
